title: Ogonna lynda Udechukwu
logo: /aimage.jpg.png
description: Data Analyst with 2 years experience using Excel for report automation, SQL for data manipulationn and Power BI for visualiztion.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
